# This is a basic workflow to help you get started with Actions

name: scala-steward

# This workflow will launch at 00:00 every Sunday
on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Launch Scala Steward
    steps:
      - uses: actions/checkout@v3.0.0
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2.14.0
        with:
          github-token: ${{ secrets.SCALA_STEWARD_TOKEN }}
          repos-file: 'repos.md'
